//! # Data Models
//!
//! This module defines all the data structures used throughout the Locate918 API.
//! These structs serve multiple purposes:
//! - Database row mapping (via SQLx's FromRow)
//! - JSON serialization for API responses (via Serde's Serialize)
//! - JSON deserialization for API requests (via Serde's Deserialize)
//!
//! ## Naming Convention
//! - `Thing` - Full database record (used in responses)
//! - `CreateThing` - Request payload for creating new records (no id/timestamps)
//!
//! ## Owner
//! Will (Coordinator/Backend Lead)

// =============================================================================
// IMPORTS
// =============================================================================

use chrono::{DateTime, Utc};           // Timestamp handling (timezone-aware)
use serde::{Deserialize, Serialize};   // JSON serialization/deserialization
use sqlx::FromRow;                     // Maps database rows to structs
use uuid::Uuid;                        // Universally unique identifiers

// =============================================================================
// EVENT MODELS
// =============================================================================
// Events are the core data type - they represent local happenings that users
// want to discover. Events are created either manually (for testing) or by
// Skylar's scraper service (in production).

/// Represents an event in the database.
///
/// # Database Table
/// `events` - See migrations/001_initial.sql
///
/// # Example JSON
/// ```json
/// {
///   "id": "550e8400-e29b-41d4-a716-446655440000",
///   "title": "Jazz Night at The Blue Note",
///   "description": "Live jazz music featuring local artists",
///   "venue": "The Blue Note",
///   "venue_address": "123 Main St, Tulsa, OK",
///   "location": "Downtown Tulsa",
///   "source_url": "https://thebluenote.com/events/jazz-night",
///   "source_name": "The Blue Note",
///   "start_time": "2026-01-25T20:00:00Z",
///   "end_time": "2026-01-25T23:00:00Z",
///   "categories": ["concerts", "jazz", "live music"],
///   "price_min": 15.00,
///   "price_max": 25.00,
///   "outdoor": false,
///   "family_friendly": false,
///   "image_url": "https://example.com/image.jpg",
///   "created_at": "2026-01-17T12:00:00Z",
///   "updated_at": "2026-01-17T12:00:00Z"
/// }
/// ```


/// Request payload for creating a new event.
///
/// # Differences from Event
/// - No `id` field (server generates it)
/// - No `created_at`/`updated_at` fields (server generates them)
///
/// # Usage
/// ```text
/// POST /api/events
/// Content-Type: application/json
///
/// {
///   "title": "Jazz Night",
///   "source_url": "https://example.com/event",
///   "start_time": "2026-01-25T20:00:00Z",
///   "categories": ["concerts", "jazz"]
/// }
/// ```


// =============================================================================
// USER MODELS
// =============================================================================
// Users represent people using the Locate918 app. User data powers
// personalization - the LLM uses preferences and interaction history
// to make relevant recommendations.

/// Represents a user account in the database.
///
/// # Database Table
/// `users` - See migrations/001_initial.sql
///
/// # Example JSON
/// ```json
/// {
///   "id": "94c99eb0-21f3-4f7e-afee-f533b964a2d4",
///   "email": "will@example.com",
///   "name": "Will",
///   "location_preference": "Downtown Tulsa",
///   "radius_miles": 15,
///   "price_max": 50.00,
///   "family_friendly_only": false,
///   "created_at": "2026-01-17T19:34:01Z",
///   "updated_at": "2026-01-17T19:34:01Z"
/// }
/// ```
#[derive(Debug, Serialize, Deserialize, FromRow)]
pub struct User {
    /// Unique identifier (UUID v4, generated by server)
    pub id: Uuid,

    /// User's email address (required, unique)
    pub email: String,

    /// Display name (optional)
    pub name: Option<String>,

    /// Preferred location/area for events (optional)
    pub location_preference: Option<String>,

    /// How far the user is willing to travel (miles)
    pub radius_miles: Option<i32>,

    /// Maximum price the user wants to pay
    pub price_max: Option<f64>,

    /// Only show family-friendly events
    pub family_friendly_only: bool,

    /// When the account was created
    pub created_at: DateTime<Utc>,

    /// When the account was last updated
    pub updated_at: DateTime<Utc>,
}

/// Request payload for creating a new user.
#[derive(Debug, Deserialize)]
pub struct CreateUser {
    pub email: String,
    pub name: Option<String>,
    pub location_preference: Option<String>,
    pub radius_miles: Option<i32>,
    pub price_max: Option<f64>,
    #[serde(default)]
    pub family_friendly_only: bool,
}

/// Request payload for updating user preferences.
#[derive(Debug, Deserialize)]
pub struct UpdateUserPreferences {
    pub location_preference: Option<String>,
    pub radius_miles: Option<i32>,
    pub price_max: Option<f64>,
    pub family_friendly_only: Option<bool>,
}

// =============================================================================
// USER PREFERENCE MODELS (Category Preferences)
// =============================================================================
// Preferences track what categories a user likes or dislikes.
// This is EXPLICIT preference data - the user told us directly.

/// Represents a user's preference for a category.
///
/// # Weight Scale
/// - +5 = Love it (always show me this)
/// - +3 = Like it
/// - +1 = Somewhat interested
/// - -1 = Somewhat disinterested
/// - -3 = Dislike
/// - -5 = Hate it (never show me this)
#[derive(Debug, Serialize, Deserialize, FromRow)]
pub struct UserPreference {
    pub id: Uuid,
    pub user_id: Uuid,
    pub category: String,
    pub weight: i32,
    pub created_at: DateTime<Utc>,
}

/// Request payload for adding/updating a category preference.
#[derive(Debug, Deserialize)]
pub struct CreateUserPreference {
    pub category: String,
    pub weight: i32,
}

// =============================================================================
// USER INTERACTION MODELS
// =============================================================================
// Interactions track what events a user has engaged with.
// This is IMPLICIT preference data - inferred from behavior.

/// Represents a user's interaction with an event.
///
/// # Interaction Types
/// - `"clicked"` - User opened the event details
/// - `"saved"` - User bookmarked the event
/// - `"dismissed"` - User clicked "not interested"
/// - `"attended"` - User marked as attending
#[derive(Debug, Serialize, Deserialize, FromRow)]
pub struct UserInteraction {
    pub id: Uuid,
    pub user_id: Uuid,
    pub event_id: Uuid,
    pub interaction_type: String,
    /// Denormalized for faster ML queries
    pub event_category: Option<String>,
    /// Denormalized for faster ML queries
    pub event_venue: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// Request payload for recording an interaction.
#[derive(Debug, Deserialize)]
pub struct CreateUserInteraction {
    pub event_id: Uuid,
    pub interaction_type: String,
}

// =============================================================================
// COMPOSITE MODELS (FOR LLM CONTEXT)
// =============================================================================

/// Complete user profile for LLM personalization.
///
/// This is the primary data structure for chat personalization.
/// Contains basic user info, category preferences, and recent interactions.
#[derive(Debug, Serialize)]
pub struct UserProfile {
    pub user: User,
    pub preferences: Vec<UserPreference>,
    pub recent_interactions: Vec<UserInteractionWithEvent>,
}

/// User interaction with event details included.
///
/// Used for displaying interaction history with context.
#[derive(Debug, Serialize, Deserialize, FromRow)]
pub struct UserInteractionWithEvent {
    pub interaction_type: String,
    pub event_title: String,
    pub event_category: Option<String>,
    pub created_at: DateTime<Utc>,
}

// =============================================================================
// SEARCH MODELS
// =============================================================================


